/** @type {import('tailwindcss').Config} */
export default {
  content: {
    files: [
      './src/**/*.{js,ts,jsx,tsx}',
      './index.html',
      './src/**/*.stories.{js,ts,jsx,tsx}',
    ],
  },
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    // Font family
    'font-sans',
    // Font weight
    'font-normal',
    'font-medium',
    'font-semibold',
    'font-bold',
    // Font size
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    // Letter spacing
    'tracking-wide',
    // Line height
    'leading-tight',
    'leading-snug',
    'leading-normal',
    'leading-relaxed',
    // Border radius
    'rounded-sm',
    'rounded-md',
    'rounded-lg',
    'rounded-xl',
    // Box shadow
    'shadow-xs',
    'shadow-sm',
    'shadow-md',
    'shadow-lg',
    // Transition timing function
    'ease-linear',
    'ease-in',
    'ease-out',
    'ease-in-out',
    // Color utilities
    'bg-background',
    'bg-foreground',
    'bg-white',
    'bg-primary',
    'bg-primary-foreground',
    'bg-secondary',
    'bg-secondary-foreground',
    'bg-muted',
    'bg-muted-foreground',
    'bg-accent',
    'bg-accent-foreground',
    'bg-destructive',
    'bg-destructive-foreground',
    'bg-line-default',
    'bg-input',
    'bg-input-background',
    'bg-switch-background',
    'bg-ring',
    'text-background',
    'text-foreground',
    'text-white',
    'text-primary',
    'text-primary-foreground',
    'text-secondary',
    'text-secondary-foreground',
    'text-muted',
    'text-muted-foreground',
    'text-accent',
    'text-accent-foreground',
    'text-destructive',
    'text-destructive-foreground',
    'text-line-default',
    'text-input',
    'text-input-background',
    'text-switch-background',
    'text-ring',
    'border-background',
    'border-foreground',
    'border-white',
    'border-primary',
    'border-primary-foreground',
    'border-secondary',
    'border-secondary-foreground',
    'border-muted',
    'border-muted-foreground',
    'border-accent',
    'border-accent-foreground',
    'border-destructive',
    'border-destructive-foreground',
    'border-line-default',
    'border-input',
    'border-input-background',
    'border-switch-background',
    'border-ring',
    // Sizing utilities
    'p-4',
    'max-w-md',
    'spacing-4',
  ],
};
